name: Deploy PR Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    if: |
      github.event.pull_request.author_association == 'OWNER' ||
      github.event.pull_request.author_association == 'COLLABORATOR' ||
      github.event.pull_request.author_association == 'MEMBER'
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows pushing to gh-pages
      pull-requests: write  # Needed for commenting

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install and Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Deploy preview to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Jekyll's default output directory
          destination_dir: preview-${{ github.event.number }}
          keep_files: true  # Keeps existing previews

      - name: Comment Preview URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "🔍 Preview your changes here: [Preview Site](https://yourusername.github.io/your-repo/preview-${{ github.event.number }}/)"
